comparisons: ".test/comparison/comparisons.tsv"
platform: "linux"
general:
  outdir: "results/comparisons/"
resources:
  annot: ".test/resources/annot/WT_vs_Meth13-CG.bed" #optional must be "" empty string if not being used
params:
  bins: TRUE
  windowSize: 1000
  stepSize: 1000
  test: F # default F, Chisq for overdispersion
  overdispersion: none # default none, NM for overdispersion
  qValue: 0.01
  minCov: 4
  minDiff: 0.4
  context: ["CG"]
  species: ""
