configfile: .test/comparison/config.yaml
default-resources: [cpus=1, mem_mb=2000, time_min=60]
use-conda: true
snakefile: workflow/comparison/Snakefile
dry-run: false
keep-going: true
latency-wait: 20
cores: all
