include: "../rules/computeDmrs.smk"
from snakemake.utils import validate
import pandas as pd

validate(config, schema="../schemas/comparison.config.schema.yaml")

comparisons = pd.read_csv(config["comparisons"], dtype=str, sep="\t").set_index(["id",], drop=False)

outdir = config['general']['outdir']
wildcard_constraints:
	id="|".join(comparisons["id"]),
	
	
def get_CX_reports(wildcards):
	u = comparisons.loc[ wildcards.id, ["control", "treatment"] ].dropna()
	return { 'control' : u.control.split(",") , 'treatment' : u.treatment.split(",") }
def get_id():
	return comparisons["id"].unique()

# report template
def all_input(wildcards):
	"""
	Function defining all requested inputs for the rule all (below).
	"""
	

	wanted_input = []

	wanted_input.extend(
		expand(
			[
			"results/comparisons/{id}/{id}-{contexts}.bed"
			] ,
			id=get_id(),
			contexts=["CG","CHG","CHH"]
		)
	)

	return wanted_input
rule all:
	input: all_input
	resources:
		cpus= 1,
		mem_mb=2000,
		time_min=140
