comparisons: "config/comparisons.tsv"
platform: "linux"
general:
  outdir: "results/comparisonsDupliqué/"
resources:
  ref:
    genome: ".test/resources/genome/Malus_domestica_cultivar_Golden_Delicious-chr4.fasta"
  annot: ".test/resources/annot/WT_vs_Meth13-CG.bed" #optional must be "" empty string if not being used
params:
  method: bins
  binSize: 500
  kernelFunction: triangular
  test: fisher
  pseudocountM: 1
  pseudocountN: 2
  pValueThreshold: 0.01
  minCytosinesCount: 1 # default 4 in bins/noise_filter , must be 1 for neighbourhood method
  minProportionDifference: 0.4
  minGap: 50
  minSize: 100
  minReadsPerCytosine: 4
  cores: 1
  context: ["CG", "CHG"]
