samples: "config/samples.tsv"
units: "config/units.tsv"


resources:
  ref:
    genome_directory: "resources/genome"
  adapters: "resources/adapters/TruSeq3-PE.fa"
    #Directory containing a fasta file with the DNA sequence of the organism sutided.
subsample:
  activate: 'true'
params:
  trimmomatic-pe:
    trimmer: "ILLUMINACLIP"
    trimmer-options: "2:30:10:2:keepBothReads LEADING:3 TRAILING:3 MINLEN:36"
    other: ""
  seqtk:
    seed: 100
    other: ""
  bismark:
    aligner: bowtie2 #bowtie2/hisat2

