comparisons: "config/comparisons.tsv"
general:
  outdir: "results/comparisonsDupliqué/"
resources:
  ref:
    genome: ".test/resources/genome/Malus_domestica_cultivar_Golden_Delicious-chr4.fasta"
params:
  method: neighbourhood
  binSize: 500
  kernelFunction: triangular
  test: fisher
  pseudocountM: 1
  pseudocountN: 2
  pValueThreshold: 0.01
  minCytosinesCount: 1 # default 4 in bins/noise_filter , must be 1
  minProportionDifference: 0.4
  minGap: 50
  minSize: 2
  minReadsPerCytosine: 4
  cores: 1
  context: ["CG"]
