comparisons: "config/comparisons.tsv"
general:
  outdir: "/path/to/output/directory"
resources:
  ref:
    genome: "/path/to/genome"
params:
  method: neighbourhood
  binSize: 500
  kernelFunction: triangular
  test: fisher
  pseudocountM: 1
  pseudocountN: 2
  pValueThreshold: 0.01
  minCytosinesCount: 4
  minProportionDifference: 0.4
  minGap: 0
  minSize: 50
  minReadsPerCytosine: 4
  cores: 1
  context: ["CG", "CHG", "CHH"]
