samples: ".test/config/samples.tsv"
units: ".test/config/units.tsv"
general:
  benchmark: 1
# these steps are user defined and will condition which part of the pipeline is executed and which output files the user requests
steps:
  # minimal vs full run
    subsample:
      activate: 'true'
  # whether to preprocess raw data or not
    trimming:
      activate: 'False'
  # whether to generate quality reports or not
    quality:
      activate: 'True'
  # whether to perform bisulfite conversion on genome and index it (preparation)
    genome_preparation:
      activate: 'True'
  # whether to perform methylation extraction
    methylation_extraction_bismark:
      activate: 'True'
    methylation_extraction_bsmap:
      activate: 'False'
  # whether to perform differential methylation calling
    methylation_calling:
      activate: 'False'
  # which reports to use True|true : bsmap ,else bismark 
    use_bsmap:
      activate: 'False'

resources:
  ref:
    genome: ".test/resources/genome/Malus_domestica_cultivar_Golden_Delicious-chr4.fasta"
    #Directory containing a fasta file with the DNA sequence of the organism sutided.
  adapters: ".test/resources/adapters"

params:
  trimmomatic-pe:
    trimmer: "ILLUMINACLIP"
    trimmer-options: "2:30:10:2:keepBothReads LEADING:3 TRAILING:3 MINLEN:36"
    extra: ""
  seqtk:
    seed: 100
    size: 10000
    extra: ""
  bismark:
    aligner: bowtie2 #bowtie2/hisat2
    instances: 2
  bsmap:
    genome: ".test/resources/genome/Malus_domestica_cultivar_Golden_Delicious-chr4.fasta"