samples: ".test/config/samples.tsv"
units: ".test/config/units.tsv"

# these steps are user defined and will condition which part of the pipeline is executed and which output files the user requests
steps:
  # minimal vs full run
    subsample:
      activate: 'True'
  # whether to preprocess raw data or not
    trimming:
      activate: 'False'
  # whether to generate read quality reports or not
    quality:
      activate: 'False'
  # whether to perform bisulfite conversion on genome and index it (preparation)
    genome_preparation:
      activate: 'False'
  # whether to generate CX reports
    methylation_extraction:
      activate: 'True'
  # whether to compute DMR's
    methylation_calling:
      activate: 'False'
    use_bsmap:
      activate: 'True'
resources:
  ref:
    genome_directory: ".test/resources/genome"
    #Directory containing a fasta file with the DNA sequence of the organism sutided.
  adapters: ".test/resources/adapters"

params:
  trimmomatic-pe:
    trimmer: "ILLUMINACLIP"
    trimmer-options: "2:30:10:2:keepBothReads LEADING:3 TRAILING:3 MINLEN:36"
    other: ""
  seqtk:
    seed: 100
    size: 10000
    other: ""
  bismark:
    aligner: bowtie2 #bowtie2/hisat2
    instances: 3
  bsmap:
    genome: ".test/resources/genome/Malus_domestica_cultivar_Golden_Delicious-chr4.fasta"